### TASK-10A: Please model the AD dataset using the SVM, Decision Tree, and Random Forest algorithms. Please apply train test split (%75-%25) Then grid search (hyperparameter tuning) Then classification report and confusion matrix (on the test dataset) Then compare the findings from the three algorithms.

In [1]:
import numpy as np
import pandas as pd

data = pd.read_excel('Temporary_data3_Left_Right_Copy.xlsx')
data.head()

SEX  EDUC  MARISTAT  INDEPEND  RESIDENC  NACCFAM  ANYMEDS  SMOKYRS  \
0    2    18         1         1         1        1        1        0   
1    1    11         1         1         1        1        1        0   
2    2    16         1         1         1        1        1       10   
3    1    14         1         1         1        0        1        0   
4    1    16         1         1         2        0        1       50   

   NACCTBI  DIABETES  ...   RSUPFR  RSUPFRM  RSUPPAR  RSUPPARM  RSUPTEM  \
0        0         0  ...  27.9038   2.2157  10.3481    1.7014  13.4250   
1        0         0  ...  29.0600   2.6900   9.2500    1.6300  14.8800   
2        0         1  ...  33.0000   2.5400  13.6900    1.5600  16.2300   
3        0         1  ...  31.6800   2.4100   9.6400    1.4500  15.1100   
4        0         0  ...  28.0631   1.9501   9.1125    1.0427  13.3763   

   RSUPTEMM  RSUPMAR  RSUPMARM  RTRTEM  RTRTEMM  
0    1.7419   9.8700    1.6792  0.8906   1.1947  
1    2.3000   7.2700    1.8900  1.3800   2.0300  
2    2.0700  10.1100    1.8400  1.0100   1.5000  
3    1.6400  10.3900    1.8300  0.7400   1.1000  
4    1.6270   7.5844    1.4595  0.6638   0.8527  

[5 rows x 186 columns]

In [2]:
from sklearn.model_selection import train_test_split
Cdrglob = data["CDRGLOB"]
data.drop(columns = ["CDRGLOB"], axis = 1, inplace = True)
X_train, X_test, y_train, y_test = train_test_split(data, Cdrglob, test_size=0.25, random_state=42)

**SVC için**

In [3]:
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import GridSearchCV

model = SVC()

param_grid = {'kernel': ['rbf','poly'],
              'shrinking':[True,False]}

grid = GridSearchCV(model, param_grid, refit=True, verbose=3)
grid.fit(X_train, y_train)
grid.best_params_

Fitting 5 folds for each of 4 candidates, totalling 20 fits
[CV 1/5] END ........kernel=rbf, shrinking=True;, score=0.443 total time=   0.1s
[CV 2/5] END ........kernel=rbf, shrinking=True;, score=0.458 total time=   0.1s
[CV 3/5] END ........kernel=rbf, shrinking=True;, score=0.463 total time=   0.1s
[CV 4/5] END ........kernel=rbf, shrinking=True;, score=0.458 total time=   0.1s
[CV 5/5] END ........kernel=rbf, shrinking=True;, score=0.463 total time=   0.1s
[CV 1/5] END .......kernel=rbf, shrinking=False;, score=0.443 total time=   0.1s
[CV 2/5] END .......kernel=rbf, shrinking=False;, score=0.458 total time=   0.2s
[CV 3/5] END .......kernel=rbf, shrinking=False;, score=0.463 total time=   0.1s
[CV 4/5] END .......kernel=rbf, shrinking=False;, score=0.458 total time=   0.1s
[CV 5/5] END .......kernel=rbf, shrinking=False;, score=0.463 total time=   0.1s
[CV 1/5] END .......kernel=poly, shrinking=True;, score=0.468 total time=   0.1s
[CV 2/5] END .......kernel=poly, shrinking=True;,

{'kernel': 'poly', 'shrinking': True}

In [5]:
grid_predictions = grid.predict(X_test)
print(confusion_matrix(y_test, grid_predictions))
print(classification_report(y_test, grid_predictions))

[[146  38   0   0]
 [ 62  46   0   0]
 [  9  30   0   0]
 [  1   7   0   0]]
              precision    recall  f1-score   support

           0       0.67      0.79      0.73       184
           1       0.38      0.43      0.40       108
           2       0.00      0.00      0.00        39
           3       0.00      0.00      0.00         8

    accuracy                           0.57       339
   macro avg       0.26      0.30      0.28       339
weighted avg       0.48      0.57      0.52       339



/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [6]:
from sklearn.tree import DecisionTreeClassifier

param_grid = {'max_depth': [1,5,10],
              'min_samples_split': [2,5,10],
              'min_samples_leaf': [1,5,10]}
grid = GridSearchCV(DecisionTreeClassifier(), param_grid, refit=True, verbose=3)
grid.fit(X_train, y_train)
grid.best_params_

Fitting 5 folds for each of 27 candidates, totalling 135 fits
[CV 1/5] END max_depth=1, min_samples_leaf=1, min_samples_split=2;, score=0.645 total time=   0.0s
[CV 2/5] END max_depth=1, min_samples_leaf=1, min_samples_split=2;, score=0.626 total time=   0.0s
[CV 3/5] END max_depth=1, min_samples_leaf=1, min_samples_split=2;, score=0.591 total time=   0.0s
[CV 4/5] END max_depth=1, min_samples_leaf=1, min_samples_split=2;, score=0.591 total time=   0.0s
[CV 5/5] END max_depth=1, min_samples_leaf=1, min_samples_split=2;, score=0.611 total time=   0.0s
[CV 1/5] END max_depth=1, min_samples_leaf=1, min_samples_split=5;, score=0.645 total time=   0.0s
[CV 2/5] END max_depth=1, min_samples_leaf=1, min_samples_split=5;, score=0.626 total time=   0.0s
[CV 3/5] END max_depth=1, min_samples_leaf=1, min_samples_split=5;, score=0.591 total time=   0.0s
[CV 4/5] END max_depth=1, min_samples_leaf=1, min_samples_split=5;, score=0.591 total time=   0.0s
[CV 5/5] END max_depth=1, min_samples_leaf=1, m

{'max_depth': 5, 'min_samples_leaf': 1, 'min_samples_split': 10}

In [7]:
grid_predictions = grid.predict(X_test)
print(confusion_matrix(y_test, grid_predictions))
print(classification_report(y_test, grid_predictions))

[[158  26   0   0]
 [ 33  61  14   0]
 [  3  14  18   4]
 [  0   1   6   1]]
              precision    recall  f1-score   support

           0       0.81      0.86      0.84       184
           1       0.60      0.56      0.58       108
           2       0.47      0.46      0.47        39
           3       0.20      0.12      0.15         8

    accuracy                           0.70       339
   macro avg       0.52      0.50      0.51       339
weighted avg       0.69      0.70      0.70       339



In [9]:
from sklearn.ensemble import RandomForestClassifier

param_grid = {'n_estimators': [10, 100, 1000],
                'max_depth': [1,5,10],
                'min_samples_leaf': [1,5,10]}
grid = GridSearchCV(RandomForestClassifier(), param_grid, refit=True, verbose=3)
grid.fit(X_train, y_train)
grid.best_params_

Fitting 5 folds for each of 27 candidates, totalling 135 fits
[CV 1/5] END max_depth=1, min_samples_leaf=1, n_estimators=10;, score=0.606 total time=   0.0s
[CV 2/5] END max_depth=1, min_samples_leaf=1, n_estimators=10;, score=0.552 total time=   0.0s
[CV 3/5] END max_depth=1, min_samples_leaf=1, n_estimators=10;, score=0.527 total time=   0.0s
[CV 4/5] END max_depth=1, min_samples_leaf=1, n_estimators=10;, score=0.547 total time=   0.0s
[CV 5/5] END max_depth=1, min_samples_leaf=1, n_estimators=10;, score=0.571 total time=   0.0s
[CV 1/5] END max_depth=1, min_samples_leaf=1, n_estimators=100;, score=0.571 total time=   0.3s
[CV 2/5] END max_depth=1, min_samples_leaf=1, n_estimators=100;, score=0.591 total time=   0.2s
[CV 3/5] END max_depth=1, min_samples_leaf=1, n_estimators=100;, score=0.552 total time=   0.3s
[CV 4/5] END max_depth=1, min_samples_leaf=1, n_estimators=100;, score=0.611 total time=   0.3s
[CV 5/5] END max_depth=1, min_samples_leaf=1, n_estimators=100;, score=0.601 to

{'max_depth': 10, 'min_samples_leaf': 5, 'n_estimators': 1000}

In [10]:
grid_predictions = grid.predict(X_test)
print(confusion_matrix(y_test, grid_predictions))
print(classification_report(y_test, grid_predictions))

[[152  32   0   0]
 [ 24  84   0   0]
 [  1  32   6   0]
 [  0   3   5   0]]
              precision    recall  f1-score   support

           0       0.86      0.83      0.84       184
           1       0.56      0.78      0.65       108
           2       0.55      0.15      0.24        39
           3       0.00      0.00      0.00         8

    accuracy                           0.71       339
   macro avg       0.49      0.44      0.43       339
weighted avg       0.71      0.71      0.69       339



/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
